version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    build: ./php
    volumes:
      - ./src:/var/www
    networks:
      - code-network

  redis:
    image: redis:5
    networks:
      - code-network

  composer:
    image: composer:1.6
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    command: composer install
    user: 1000:1000

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: phonebook
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    networks:
      - code-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
